### ISSUE TITLE
Output node names

### ISSUE THREAD

**Issue by vagi8** [CMU-Perceptual-Computing-Lab/openpose#1707]
### Issue Summary
I am planning to convert your caffe model to tensorflow lite. for which i ll be needing your output node names (for the command `tensorflowjs_converter` ) 
i use ccaffe-tensorflow and generated a pb inference graph. 
when i try to put it in tensorboard/ netron, i am unable to discern the output node name. 
Please Help.

### Executed Command (if any)
I tried output node names as the following 
'import/Mconv7_stage6/BiasAdd'
'BiasAdd'

### OpenPose Output (if any)
N/A

### Errors (if any)
KeyError: "The name 'import/Mconv7_stage6/BiasAdd' refers to an Operation not in the graph."

### Type of Issue
- Help wanted
- Question

### Your System Configuration
1. `Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/tfjs/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 757, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 761, in main
    convert(argv[0].split(' '))
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 744, in convert
    experiments=args.experiments)
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 433, in convert_tf_frozen_model
    experiments=experiments)
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 135, in optimize_graph
    graph.add_to_collection('train_op', graph.get_operation_by_name(name))
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3798, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3670, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/ai/anaconda3/envs/tfjs/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3730, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'import/Mconv7_stage6/BiasAdd' refers to an Operation not in the graph."`

2. **OpenPose version**: 
OpenPose v1.6.0

3. **General configuration**:
    - **Installation mode**: CMake 
    - **Operating system** : Ubuntu 18.04.4 LTS
    - **Operating system version**: 18
    - **Release or Debug mode**: release
    - **Compiler**: Gcc 7.5.0

4. **Non-default settings**:
N/A

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.17.0
    - **OpenCV version**: 3.2.0

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10.1.243
    - **GPU model** (`nvidia-smi` in Ubuntu): GTX 1060 6GB

7. If **CPU-only mode** issue:
N/A

8. If **Python** API:
N/A

9. If **Windows** system:
N/A

10. If **speed performance** issue:
N/A

**Comment by gineshidalgo99** [comment]
Not familiar with TensorFlow, what is exactly what you need help with?
