### ISSUE TITLE
[Ubuntu 16]pip is already up-to-date(9.0.1) but was told using older version of pip during installation

### ISSUE THREAD

**Issue by Fung-yuantao** [CMU-Perceptual-Computing-Lab/openpose#279]
### Issue Summary
When executing `bash ./ubuntu/install_cmake.sh`, it said that the pip version was 8.x(I have forgot the exact number) but I am pretty sure I have upgraded pip to version 9.0.1 and  the result of `pip --version` is `pip 9.0.1 from /home/tao/.local/lib/python2.7/site-packages (python 2.7)`. 
The first time that I ran script `install_cmake.sh`, I thought it successfully installed everything(no errors, but just warnings that told me the version of pip is 8.x while the newest version is 9.0.1) and then I tried to configure using `cmake_gui`, which reported errors like `cuDNN not found` and `CUDA not found`, etc., though CUDA did get installed because the result of `sudo apt-get install cuda` was `cuda is already the newest version (8.0.61-1).`
Then I tried to install using the second method - Script Compilation. I merged the contents on `cuda/ `folders to `cuda-8.0/`, ran `sudo apt-get install libopencv-dev` and `sudo apt-get install libatlas-base-dev`, but got a lot errors(too much to post here) when running `bash ./ubuntu/install_caffe_and_openpose_if_cuda8.sh`.
After all that, I ran `bash ./ubuntu/install_cmake.sh` again, and this time it reported a python error while installing cuDNN:
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==9.0.1' distribution was not found and is required by the application
```

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
**Installation mode**: I tried CMake first, then sh script installation (Ubuntu).
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): check using command `sudo apt-get install cuda`:
```shell
$ sudo apt-get install cuda
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cuda is already the newest version (8.0.61-1).
0 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
```
**cuDNN version**: failed to install.
**GPU model** (`nvidia-smi` in Ubuntu):
```shell
$ nvidia-smi
Thu Oct 12 11:48:56 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
|  0%   43C    P8    11W / 220W |    405MiB /  8112MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1023    G   /usr/lib/xorg/Xorg                             222MiB |
|    0      1713    G   compiz                                         113MiB |
|    0      2329    G   ...el-token=CB8E6DFE258BA1218928CDB731BACAF6    66MiB |
+-----------------------------------------------------------------------------+
```
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**:
```shell
$ sudo apt-get install libopencv-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopencv-dev is already the newest version (2.4.9.1+dfsg-1.5ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
```
Compiler (`gcc --version` in Ubuntu):
```shell
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Fung-yuantao** [comment]
It seems that the problem is not `pip`. I reinstall ubuntu 16.04 and ran every command in `./ubuntu/install_cmake.sh` seperately, and found some errors popped up when installing cuda:
```shell
/sbin/ldconfig.real: /usr/lib/nvidia-375/libEGL.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/lib32/nvidia-375/libEGL.so.1 is not a symbolic link
```
The solution from [here](https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-375/+bug/1662860) did help me a lot:
```shell
$ sudo mv /usr/lib/nvidia-375/libEGL.so.1 /usr/lib/nvidia-375/libEGL.so.1.org
$ sudo mv /usr/lib32/nvidia-375/libEGL.so.1 /usr/lib32/nvidia-375/libEGL.so.1.org
$ sudo ln -s /usr/lib/nvidia-375/libEGL.so.1 /usr/lib/nvidia-375/libEGL.so.375.39
$ sudo ln -s /usr/lib32/nvidia-375/libEGL.so.1 /usr/lib32/nvidia-375/libEGL.so.375.39
```
Then I ran the remaining commands to install cuDNN, etc. Everything went smoothly this time, and the `cmake_gui` can finally discover cuda and cuDNN.
