### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sophia-wright-blue** [CMU-Perceptual-Computing-Lab/openpose#869]
### Issue Summary

I get the error ```Segmentation fault (core dumped)```  on running ```./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_video output/video.avi --logging_level 0 --no_display --disable_multi_thread```

### Executed Command (if any)
```./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_video output/video.avi --logging_level 0 --no_display --disable_multi_thread```

### OpenPose Output (if any)
```Segmentation fault (core dumped)``` 

### Errors (if any)
```Segmentation fault (core dumped)``` 

### Backtrace

```
 gdb ./build/examples/openpose/openpose.bin

(gdb) catch signal SIGSEGV

(gdb) r --video examples/media/video.avi --write_video output/video.avi --logging_level 0 --no_display --disable_multi_threadStarting program: /home/sophia/open2/openpose/build/examples/openpose/openpose.bin --video examples/media/video.avi --write_video output/video.avi --logging_level 0 --no_display --disable_multi_thread
[Thread debugging using libthread_db enabled]


Catchpoint 1 (signal SIGSEGV), 0x00007ffff7020826 in google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const () from /anaconda/envs/pose2/lib/libopencv_dnn.so.3.4
(gdb) bt
#0  0x00007ffff7020826 in google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const ()
   from /anaconda/envs/pose2/lib/libopencv_dnn.so.3.4
#1  0x00007ffff707445d in google::protobuf::FileDescriptorProto::New(google::protobuf::Arena*) const ()
   from /anaconda/envs/pose2/lib/libopencv_dnn.so.3.4
#2  0x00007ffff0646038 in google::protobuf::MessageLite::ParseFromArray(void const*, int) ()
   from /usr/lib/x86_64-linux-gnu/libprotobuf.so.9
#3  0x00007ffff068f1b6 in google::protobuf::EncodedDescriptorDatabase::Add(void const*, int) ()
   from /usr/lib/x86_64-linux-gnu/libprotobuf.so.9
#4  0x00007ffff06509b8 in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) ()
   from /usr/lib/x86_64-linux-gnu/libprotobuf.so.9
#5  0x00007ffff067f48c in google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto() ()
   from /usr/lib/x86_64-linux-gnu/libprotobuf.so.9
#6  0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=9, argv=argv@entry=0x7fffffffd8c8,
    env=env@entry=0x7fffffffd918) at dl-init.c:72
#7  0x00007ffff7de77cb in call_init (env=0x7fffffffd918, argv=0x7fffffffd8c8, argc=9, l=<optimized out>) at dl-init.c:30
#8  _dl_init (main_map=0x7ffff7ffe168, argc=9, argv=0x7fffffffd8c8, env=0x7fffffffd918) at dl-init.c:120
#9  0x00007ffff7dd7c6a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#10 0x0000000000000009 in ?? ()
#11 0x00007fffffffdbea in ?? ()
#12 0x00007fffffffdc2f in ?? ()
#13 0x00007fffffffdc37 in ?? ()
#14 0x00007fffffffdc50 in ?? ()
#15 0x00007fffffffdc5e in ?? ()
#16 0x00007fffffffdc6f in ?? ()
#17 0x00007fffffffdc7f in ?? ()
#18 0x00007fffffffdc81 in ?? ()
#19 0x00007fffffffdc8e in ?? ()
#20 0x0000000000000000 in ?? ()

```

### Type of Issue

- Execution error
- Help wanted

### Your System Configuration

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** (`lsb_release -a` in Ubuntu):
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
    - Compiler: 5.4.0, ... (Ubuntu); 
- **OpenCV version**: 3.4

6. If **GPU mode** issue:
    - **CUDA version**: Cuda compilation tools, release 9.2, V9.2.148

    - **GPU model** : Tesla K80

8. If **Python** API:
    - **Python version**: 2.7

======================

Any help fixing this would be greatly appreciated

**Comment by gineshidalgo99** [comment]
Could you try with the latest OpenCV? I made it work on OpenCV 4.X (at least beta and release candidate versions). I will not check nor try to make it work with 3.X given that 4 is out (so we maintain 2.4.X and 4.X). Thanks!
